application: APPLICATION_NAME
version: 1
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/files/favicon.ico
  upload: static/files/favicon.ico
 
- url: /robots.txt
  static_files: static/files/robots.txt
  upload: static/files/robots.txt
 

- url: /static
  static_dir: static

- url: .*
  script: main.py
